// import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/app/globals.css";
import connectDB from '@/lib/db.js';
// import NavBar from '@/app/components/NavBar';
import NavBar from '@/app/components/NavBarServer';

// import { getServerSession } from 'next-auth';  // provides session object for server-side pages
// import { authOptions } from '@/app/api/auth/[...nextauth]/route';

// Connect to MongoDB
connectDB();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


// export const metadata: Metadata = {
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  // const session = await getServerSession(authOptions);
  return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/* <NavBar session={session} /> */}
          <NavBar />
          {children}
        </body>
      </html>
  );
}
